logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    ec.kruger.vaccination: INFO

management:
  metrics:
    export:
      prometheus:
        enabled: false
spring:
  devtools:
    restart:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
    hikari:
      poolName: Hikari
      auto-commit: true
    liquibase:
      contexts: dev
      default-schema: krg_vaccination_security
      database-change-log-lock-table: databasechangeloglock
      database-change-log-table: databasechangelog
      drop-first: false
      test-rollback-on-update: false
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    contexts: dev

server:
  port: 9080
# application:
application:
  resources-id: vaccination
  admin: ROLE_ADMIN
  employee: ROLE_EMPLOYEE
  vaccines: SPUTNIK,ASTRAZENECA,PFIZER,JHONSON&JHONSON